dbName: simulator
dbUrl: mongodb://127.0.0.1:27017
gtp5gTunnelInfo:
  tunDev: rantun
  path: ./lib/libgtp5gnl/tools
amfSctpEndpoint:
  ips:
    - 192.168.2.114
  port: 38415
ranSctpEndpoint:
  ips:
    - 192.168.2.62
  port: 8088
ranGtpUri:
  ip: 192.168.2.62
  port: 2152
upfUriList:
- ip: 192.168.2.111
  port: 2152
ranName: ran1
gnbId:
  plmnId:
    mcc: 208
    mnc: 93
  length: 24
  value: 000001
taiList:
- tac: 1
  plmnList:
  - plmnId:
      mcc: 208
      mnc: 93
    snssaiList:
      - sst: 1
        sd: 010203
      - sst: 1
        sd: 112233
apiServerAddr: 192.168.2.62:9999
ueInfoFile:
  - uecfg.conf
tunDev: uetun
listenIp: 192.168.2.62
#all logging levels
#panic
#fatal
#error
#warn
#info
#debug
#trace
logger:
# network function
  debugLevel: info
  ReportCaller: false
